In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.cross_validation import train_test_split


In [43]:
df=pd.read_csv('bike_sharing.csv')


In [51]:
X = dataset.ix[:,[2,6,7,10]].values
print("X Values")
print(X, X.shape)

X Values
[[ 1.    0.    6.    0.24]
 [ 1.    0.    6.    0.22]
 [ 1.    0.    6.    0.22]
 ..., 
 [ 1.    0.    1.    0.26]
 [ 1.    0.    1.    0.26]
 [ 1.    0.    1.    0.26]] (17379, 4)


In [56]:
dataset=pd.read_csv('bike_sharing.csv')
y = dataset.iloc[:, 10].values
print("y Values")
y = y.reshape(17379,1)
print(y ,y.shape)


y Values
[[ 0.24]
 [ 0.22]
 [ 0.22]
 ..., 
 [ 0.26]
 [ 0.26]
 [ 0.26]] (17379, 1)


In [64]:
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)


In [65]:
print(X.shape, y.shape, type(X), type(y))

(17379, 4) (17379, 1) <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)


In [67]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(11586, 4) (5793, 4) (11586, 1) (5793, 1)


In [69]:
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)



/home/admin100/anaconda3/lib/python3.5/site-packages/sklearn/svm/base.py:216: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return column_or_1d(y, warn=True).astype(np.float64)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [79]:
y_pred = regressor.predict(X_test)
y_pred = sc_y.inverse_transform(y_pred)

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(X_test, y_pred)
# accuracy_score(y_train_set, y_pred_train) * 100

ValueError: Can't handle mix of continuous-multioutput and continuous

In [82]:
regressor.score(X_test, y_pred)

1.0